<?php
/**
 * Plugin Name: YouTube for WordPress Pro
 * Plugin URI: https://jameswelbes.com/youtube-for-wordpress
 * Description: Adds Pro features to YouTube for WordPress.
 * Version: 1.0.5
 * Requires at least: 5.8
 * Requires PHP: 7.4
 * Author: James Welbes
 * Author URI: https://jameswelbes.com
 * Text Domain: yt-for-wp-pro
 * Domain Path: /languages
 * License: GPL v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */

namespace YouTubeForWPPro;

// Exit if accessed directly.
if (!defined('ABSPATH')) {
    exit;
}

// Define plugin constants.
define( 'YOUTUBEFORWORDPRESS_PRO', __FILE__ );
define('YOUTUBE_FOR_WP_PRO_VERSION', '1.0.5');
define('YT_FOR_WP_PRO_PATH', plugin_dir_path(__FILE__));
define('YT_FOR_WP_PRO_URL', plugin_dir_url(__FILE__));

// Include plugin.php for is_plugin_active().
if (!function_exists('is_plugin_active')) {
    require_once ABSPATH . 'wp-admin/includes/plugin.php';
}

if ( file_exists( plugin_dir_path( __FILE__ ) . 'EDD_Licensing.php' ) ) {
    require plugin_dir_path( __FILE__ ) . 'EDD_Licensing.php';
}

require_once plugin_dir_path(__FILE__) . 'includes/simple-youtube-feed/pro-save.php';
require_once plugin_dir_path(__FILE__) . 'includes/youtube-live/pro-save.php';
require_once plugin_dir_path(__FILE__) . 'includes/pro-settings.php';
require_once plugin_dir_path(__FILE__) . 'includes/ajax-handlers.php';
require_once plugin_dir_path(__FILE__) . 'includes/functions.php';

/**
 * Check if the free version is active.
 *
 * @return bool
 */
function is_free_version_active() {
    return defined('YOUTUBE_FOR_WP_ACTIVE') && YOUTUBE_FOR_WP_ACTIVE;
}


/**
 * Check dependencies on activation.
 */
function activation_check() {
    if (!is_free_version_active()) {
        deactivate_plugins(plugin_basename(__FILE__));
        wp_die(
            esc_html__(
                'YouTube for WordPress Pro requires the free version of YouTube for WordPress to be installed and active.',
                'yt-for-wp-pro'
            ),
            esc_html__('Plugin Dependency Error', 'yt-for-wp-pro'),
            ['back_link' => true]
        );
    }
}
register_activation_hook(__FILE__, __NAMESPACE__ . '\\activation_check');

/**
 * Load Pro functionality if the free version is active.
 */
function load_pro_plugin() {
    if (!is_free_version_active()) {
        return;
    }

    // Include required files for Video CPT.
    require_once YT_FOR_WP_PRO_PATH . 'includes/pro-features/class-video-post-type.php';


    // Initialize the Video Post Type
    \YouTubeForWPPro\VideoCPT\Video_Post_Type::init();


    // Initialize Pro features.
    add_action('plugins_loaded', function () {
        do_action('yt_for_wp_pro_loaded');
    });
}
add_action('plugins_loaded', __NAMESPACE__ . '\\load_pro_plugin');

add_action('enqueue_block_editor_assets', function () {
    // Include the asset file generated by the build process
    $asset_file = include plugin_dir_path(__FILE__) . 'build/index.asset.php';

    wp_enqueue_script(
        'yt-for-wp-pro-block-editor',
        plugins_url('build/index.js', __FILE__), // Single bundled file
        $asset_file['dependencies'], // Properly extracted dependencies
        $asset_file['version'],      // Properly extracted version
        true
    );
});

add_action('wp_enqueue_scripts', function () {
    // Include the asset file generated by the build process
    $asset_file = include plugin_dir_path(__FILE__) . 'build/index.asset.php';

    wp_enqueue_script(
        'yt-for-wp-pro-view',
        plugins_url('build/index.js', __FILE__), // Same bundled file
        $asset_file['dependencies'], // Properly extracted dependencies
        $asset_file['version'],      // Properly extracted version
        true
    );

    if (is_singular('yt-4-wp-video')) {
        // Enqueue the CSS file
        wp_enqueue_style(
            'yt-for-wp-pro-single-video-css',
            YT_FOR_WP_PRO_URL . 'assets/css/single-video.css',
            [],
            YOUTUBE_FOR_WP_PRO_VERSION
        );
    }
});

add_action('admin_enqueue_scripts', function ($hook_suffix) {
    // Only enqueue on the Import Videos page
    if ('yt-for-wp_page_yt-for-wp-import-videos' !== $hook_suffix) {
        return;
    }

    wp_enqueue_script(
        'yt-for-wp-pro-video-import',
        YT_FOR_WP_PRO_URL . 'assets/js/video-import.js',
        ['jquery'],
        YOUTUBE_FOR_WP_PRO_VERSION,
        true
    );
    

    wp_localize_script('yt-for-wp-pro-video-import', 'ytForWPPro', [
        'nonce' => wp_create_nonce('yt-for-wp-import-videos'),
        'ajaxUrl' => admin_url('admin-ajax.php'),
    ]);
});



/**
 * Adds the plugin license page to the admin menu.
 *
 * @return void
 */
// if (function_exists('gutenberg_market_licensing')) {
// 	return;
// } else {
    function license_page() {
        error_log("license page");
    
        add_settings_section(
            'youtubeforwordpress_pro_license',
            __( 'License' ),
            'YouTubeForWPPro\EDDLicensing\license_key_settings_section',
            YOUTUBEFORWORDPRESSPRO_PLUGIN_LICENSE_PAGE
        );
    
        add_settings_field(
            'youtubeforwordpress_pro_license_key',
            '<label for="youtubeforwordpress_pro_license_key">' . __( 'License Key' ) . '</label>',
            'YouTubeForWPPro\EDDLicensing\license_key_settings_field',
            YOUTUBEFORWORDPRESSPRO_PLUGIN_LICENSE_PAGE,
            'youtubeforwordpress_pro_license',
        );
    
        ?>
        <div class="wrap">
            <h2><?php esc_html_e( 'License Options' ); ?></h2>
            <form method="post" action="options.php">
    
                <?php
                do_settings_sections( YOUTUBEFORWORDPRESSPRO_PLUGIN_LICENSE_PAGE );
                settings_fields( 'youtubeforwordpress_pro_license' );
                submit_button();
                ?>
    
            </form>
        <?php
    }

    /**
 * Adds Pro-specific admin menu items.
 */
// Add Pro-specific submenus under 'roadmapwp-menu'
add_action('admin_menu', function() {
    

    // Add License page under RoadMap menu
    add_submenu_page(
        'youtube-for-wordpress-settings', // Ensure parent menu is the same
        __('License', 'yt-for-wp-pro'),
        __('License', 'yt-for-wp-pro'),
        'manage_options',
        'youtubeforwordpresspro-license',
        'YouTubeForWPPro\license_page' // Directly call the license page function
    );
    add_submenu_page(
        'youtube-for-wordpress-settings', // Parent slug (main menu item)
        __('Import Videos', 'yt-for-wp-pro'), // Page title
        __('Import Videos', 'yt-for-wp-pro'), // Menu title
        'manage_options', // Capability
        'yt-for-wp-import-videos', // Menu slug
        'YouTubeForWPPro\Settings\render_import_videos_page' // Callback function
    );

}, 20);

add_filter('template_include', function ($template) {
    if (is_singular('yt-4-wp-video')) {
        // Path to your custom template
        $custom_template = YT_FOR_WP_PRO_PATH . 'templates/single-video.php';
        if (file_exists($custom_template)) {
            return $custom_template;
        }
    }
    return $template;
});
